---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.32
    hooks:
      - id: pymarkdown
        args:
          - -d
          - MD013
          - --strict
          - scan
  - repo: https://github.com/AlexanderDokuchaev/md-dead-link-check
    rev: v1.2.0
    hooks:
      - id: md-dead-link-check
  - repo: https://github.com/crate-ci/typos
    rev: v1
    hooks:
      - id: typos
  - repo: https://github.com/rvben/rumdl-pre-commit
    rev: v0.0.153
    hooks:
      - id: rumdl
...
