# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.22
    hooks:
      - id: pymarkdown
        args:
          - -d
          - MD013
          - --strict
          - scan
  - repo: https://github.com/AlexanderDokuchaev/md-dead-link-check
    rev: v0.9
    hooks:
      - id: md-dead-link-check
